# Generated by Django 3.0.8 on 2020-11-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201127_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fisrt_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=30, verbose_name='ИМЯ'),
        ),
    ]
